name: Pinbo
options:
  bundleIdPrefix: com.pinbo
  deploymentTarget:
    iOS: "14.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "" # 填入你的 Apple 开发者 Team ID 才能真机运行
    CODE_SIGN_STYLE: Automatic

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 6.0.0

targets:
  Pinbo:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Core
      - path: iOS-App
    dependencies:
      - package: SnapKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pinbo.app
        INFOPLIST_FILE: iOS-App/Info.plist
        TARGETED_DEVICE_FAMILY: "1" # iPhone
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_BITCODE: NO
        GENERATE_INFOPLIST_FILE: NO
